/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ManageAddressIndexRouteImport } from './routes/manage-address/index'
import { Route as MakeProfileIndexRouteImport } from './routes/make-profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as MakeProfileSellerIndexRouteImport } from './routes/make-profile/seller/index'
import { Route as MakeProfileRiderIndexRouteImport } from './routes/make-profile/rider/index'
import { Route as MakeProfileCustomerIndexRouteImport } from './routes/make-profile/customer/index'
import { Route as dashboardSellerIndexRouteImport } from './routes/(dashboard)/seller/index'
import { Route as dashboardRiderIndexRouteImport } from './routes/(dashboard)/rider/index'
import { Route as dashboardCustomerIndexRouteImport } from './routes/(dashboard)/customer/index'
import { Route as dashboardSellerLayoutRouteImport } from './routes/(dashboard)/seller/_layout'
import { Route as dashboardRiderLayoutRouteImport } from './routes/(dashboard)/rider/_layout'
import { Route as dashboardCustomerLayoutRouteImport } from './routes/(dashboard)/customer/_layout'
import { Route as dashboardSellerMypageIndexRouteImport } from './routes/(dashboard)/seller/mypage/index'
import { Route as dashboardSellerManageIndexRouteImport } from './routes/(dashboard)/seller/manage/index'
import { Route as dashboardSellerManageSettlementIdDetailRouteImport } from './routes/(dashboard)/seller/manage/$settlementId/detail'

const dashboardSellerRouteImport = createFileRoute('/(dashboard)/seller')()
const dashboardRiderRouteImport = createFileRoute('/(dashboard)/rider')()
const dashboardCustomerRouteImport = createFileRoute('/(dashboard)/customer')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSellerRoute = dashboardSellerRouteImport.update({
  id: '/(dashboard)/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRiderRoute = dashboardRiderRouteImport.update({
  id: '/(dashboard)/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardCustomerRoute = dashboardCustomerRouteImport.update({
  id: '/(dashboard)/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAddressIndexRoute = ManageAddressIndexRouteImport.update({
  id: '/manage-address/',
  path: '/manage-address/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeProfileIndexRoute = MakeProfileIndexRouteImport.update({
  id: '/make-profile/',
  path: '/make-profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeProfileSellerIndexRoute = MakeProfileSellerIndexRouteImport.update({
  id: '/make-profile/seller/',
  path: '/make-profile/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeProfileRiderIndexRoute = MakeProfileRiderIndexRouteImport.update({
  id: '/make-profile/rider/',
  path: '/make-profile/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeProfileCustomerIndexRoute =
  MakeProfileCustomerIndexRouteImport.update({
    id: '/make-profile/customer/',
    path: '/make-profile/customer/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardSellerIndexRoute = dashboardSellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardSellerRoute,
} as any)
const dashboardRiderIndexRoute = dashboardRiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRiderRoute,
} as any)
const dashboardCustomerIndexRoute = dashboardCustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardCustomerRoute,
} as any)
const dashboardSellerLayoutRoute = dashboardSellerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => dashboardSellerRoute,
} as any)
const dashboardRiderLayoutRoute = dashboardRiderLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => dashboardRiderRoute,
} as any)
const dashboardCustomerLayoutRoute = dashboardCustomerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => dashboardCustomerRoute,
} as any)
const dashboardSellerMypageIndexRoute =
  dashboardSellerMypageIndexRouteImport.update({
    id: '/mypage/',
    path: '/mypage/',
    getParentRoute: () => dashboardSellerRoute,
  } as any)
const dashboardSellerManageIndexRoute =
  dashboardSellerManageIndexRouteImport.update({
    id: '/manage/',
    path: '/manage/',
    getParentRoute: () => dashboardSellerRoute,
  } as any)
const dashboardSellerManageSettlementIdDetailRoute =
  dashboardSellerManageSettlementIdDetailRouteImport.update({
    id: '/manage/$settlementId/detail',
    path: '/manage/$settlementId/detail',
    getParentRoute: () => dashboardSellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/make-profile': typeof MakeProfileIndexRoute
  '/manage-address': typeof ManageAddressIndexRoute
  '/signup': typeof SignupIndexRoute
  '/customer': typeof dashboardCustomerLayoutRoute
  '/rider': typeof dashboardRiderLayoutRoute
  '/seller': typeof dashboardSellerLayoutRoute
  '/customer/': typeof dashboardCustomerIndexRoute
  '/rider/': typeof dashboardRiderIndexRoute
  '/seller/': typeof dashboardSellerIndexRoute
  '/make-profile/customer': typeof MakeProfileCustomerIndexRoute
  '/make-profile/rider': typeof MakeProfileRiderIndexRoute
  '/make-profile/seller': typeof MakeProfileSellerIndexRoute
  '/seller/manage': typeof dashboardSellerManageIndexRoute
  '/seller/mypage': typeof dashboardSellerMypageIndexRoute
  '/seller/manage/$settlementId/detail': typeof dashboardSellerManageSettlementIdDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/make-profile': typeof MakeProfileIndexRoute
  '/manage-address': typeof ManageAddressIndexRoute
  '/signup': typeof SignupIndexRoute
  '/customer': typeof dashboardCustomerIndexRoute
  '/rider': typeof dashboardRiderIndexRoute
  '/seller': typeof dashboardSellerIndexRoute
  '/make-profile/customer': typeof MakeProfileCustomerIndexRoute
  '/make-profile/rider': typeof MakeProfileRiderIndexRoute
  '/make-profile/seller': typeof MakeProfileSellerIndexRoute
  '/seller/manage': typeof dashboardSellerManageIndexRoute
  '/seller/mypage': typeof dashboardSellerMypageIndexRoute
  '/seller/manage/$settlementId/detail': typeof dashboardSellerManageSettlementIdDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/make-profile/': typeof MakeProfileIndexRoute
  '/manage-address/': typeof ManageAddressIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/(dashboard)/customer': typeof dashboardCustomerRouteWithChildren
  '/(dashboard)/customer/_layout': typeof dashboardCustomerLayoutRoute
  '/(dashboard)/rider': typeof dashboardRiderRouteWithChildren
  '/(dashboard)/rider/_layout': typeof dashboardRiderLayoutRoute
  '/(dashboard)/seller': typeof dashboardSellerRouteWithChildren
  '/(dashboard)/seller/_layout': typeof dashboardSellerLayoutRoute
  '/(dashboard)/customer/': typeof dashboardCustomerIndexRoute
  '/(dashboard)/rider/': typeof dashboardRiderIndexRoute
  '/(dashboard)/seller/': typeof dashboardSellerIndexRoute
  '/make-profile/customer/': typeof MakeProfileCustomerIndexRoute
  '/make-profile/rider/': typeof MakeProfileRiderIndexRoute
  '/make-profile/seller/': typeof MakeProfileSellerIndexRoute
  '/(dashboard)/seller/manage/': typeof dashboardSellerManageIndexRoute
  '/(dashboard)/seller/mypage/': typeof dashboardSellerMypageIndexRoute
  '/(dashboard)/seller/manage/$settlementId/detail': typeof dashboardSellerManageSettlementIdDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/make-profile'
    | '/manage-address'
    | '/signup'
    | '/customer'
    | '/rider'
    | '/seller'
    | '/customer/'
    | '/rider/'
    | '/seller/'
    | '/make-profile/customer'
    | '/make-profile/rider'
    | '/make-profile/seller'
    | '/seller/manage'
    | '/seller/mypage'
    | '/seller/manage/$settlementId/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/make-profile'
    | '/manage-address'
    | '/signup'
    | '/customer'
    | '/rider'
    | '/seller'
    | '/make-profile/customer'
    | '/make-profile/rider'
    | '/make-profile/seller'
    | '/seller/manage'
    | '/seller/mypage'
    | '/seller/manage/$settlementId/detail'
  id:
    | '__root__'
    | '/'
    | '/login/'
    | '/make-profile/'
    | '/manage-address/'
    | '/signup/'
    | '/(dashboard)/customer'
    | '/(dashboard)/customer/_layout'
    | '/(dashboard)/rider'
    | '/(dashboard)/rider/_layout'
    | '/(dashboard)/seller'
    | '/(dashboard)/seller/_layout'
    | '/(dashboard)/customer/'
    | '/(dashboard)/rider/'
    | '/(dashboard)/seller/'
    | '/make-profile/customer/'
    | '/make-profile/rider/'
    | '/make-profile/seller/'
    | '/(dashboard)/seller/manage/'
    | '/(dashboard)/seller/mypage/'
    | '/(dashboard)/seller/manage/$settlementId/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MakeProfileIndexRoute: typeof MakeProfileIndexRoute
  ManageAddressIndexRoute: typeof ManageAddressIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  dashboardCustomerRoute: typeof dashboardCustomerRouteWithChildren
  dashboardRiderRoute: typeof dashboardRiderRouteWithChildren
  dashboardSellerRoute: typeof dashboardSellerRouteWithChildren
  MakeProfileCustomerIndexRoute: typeof MakeProfileCustomerIndexRoute
  MakeProfileRiderIndexRoute: typeof MakeProfileRiderIndexRoute
  MakeProfileSellerIndexRoute: typeof MakeProfileSellerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/seller': {
      id: '/(dashboard)/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof dashboardSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/rider': {
      id: '/(dashboard)/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof dashboardRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/customer': {
      id: '/(dashboard)/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof dashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-address/': {
      id: '/manage-address/'
      path: '/manage-address'
      fullPath: '/manage-address'
      preLoaderRoute: typeof ManageAddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-profile/': {
      id: '/make-profile/'
      path: '/make-profile'
      fullPath: '/make-profile'
      preLoaderRoute: typeof MakeProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-profile/seller/': {
      id: '/make-profile/seller/'
      path: '/make-profile/seller'
      fullPath: '/make-profile/seller'
      preLoaderRoute: typeof MakeProfileSellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-profile/rider/': {
      id: '/make-profile/rider/'
      path: '/make-profile/rider'
      fullPath: '/make-profile/rider'
      preLoaderRoute: typeof MakeProfileRiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-profile/customer/': {
      id: '/make-profile/customer/'
      path: '/make-profile/customer'
      fullPath: '/make-profile/customer'
      preLoaderRoute: typeof MakeProfileCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/seller/': {
      id: '/(dashboard)/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof dashboardSellerIndexRouteImport
      parentRoute: typeof dashboardSellerRoute
    }
    '/(dashboard)/rider/': {
      id: '/(dashboard)/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof dashboardRiderIndexRouteImport
      parentRoute: typeof dashboardRiderRoute
    }
    '/(dashboard)/customer/': {
      id: '/(dashboard)/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof dashboardCustomerIndexRouteImport
      parentRoute: typeof dashboardCustomerRoute
    }
    '/(dashboard)/seller/_layout': {
      id: '/(dashboard)/seller/_layout'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof dashboardSellerLayoutRouteImport
      parentRoute: typeof dashboardSellerRoute
    }
    '/(dashboard)/rider/_layout': {
      id: '/(dashboard)/rider/_layout'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof dashboardRiderLayoutRouteImport
      parentRoute: typeof dashboardRiderRoute
    }
    '/(dashboard)/customer/_layout': {
      id: '/(dashboard)/customer/_layout'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof dashboardCustomerLayoutRouteImport
      parentRoute: typeof dashboardCustomerRoute
    }
    '/(dashboard)/seller/mypage/': {
      id: '/(dashboard)/seller/mypage/'
      path: '/mypage'
      fullPath: '/seller/mypage'
      preLoaderRoute: typeof dashboardSellerMypageIndexRouteImport
      parentRoute: typeof dashboardSellerRoute
    }
    '/(dashboard)/seller/manage/': {
      id: '/(dashboard)/seller/manage/'
      path: '/manage'
      fullPath: '/seller/manage'
      preLoaderRoute: typeof dashboardSellerManageIndexRouteImport
      parentRoute: typeof dashboardSellerRoute
    }
    '/(dashboard)/seller/manage/$settlementId/detail': {
      id: '/(dashboard)/seller/manage/$settlementId/detail'
      path: '/manage/$settlementId/detail'
      fullPath: '/seller/manage/$settlementId/detail'
      preLoaderRoute: typeof dashboardSellerManageSettlementIdDetailRouteImport
      parentRoute: typeof dashboardSellerRoute
    }
  }
}

interface dashboardCustomerRouteChildren {
  dashboardCustomerLayoutRoute: typeof dashboardCustomerLayoutRoute
  dashboardCustomerIndexRoute: typeof dashboardCustomerIndexRoute
}

const dashboardCustomerRouteChildren: dashboardCustomerRouteChildren = {
  dashboardCustomerLayoutRoute: dashboardCustomerLayoutRoute,
  dashboardCustomerIndexRoute: dashboardCustomerIndexRoute,
}

const dashboardCustomerRouteWithChildren =
  dashboardCustomerRoute._addFileChildren(dashboardCustomerRouteChildren)

interface dashboardRiderRouteChildren {
  dashboardRiderLayoutRoute: typeof dashboardRiderLayoutRoute
  dashboardRiderIndexRoute: typeof dashboardRiderIndexRoute
}

const dashboardRiderRouteChildren: dashboardRiderRouteChildren = {
  dashboardRiderLayoutRoute: dashboardRiderLayoutRoute,
  dashboardRiderIndexRoute: dashboardRiderIndexRoute,
}

const dashboardRiderRouteWithChildren = dashboardRiderRoute._addFileChildren(
  dashboardRiderRouteChildren,
)

interface dashboardSellerRouteChildren {
  dashboardSellerLayoutRoute: typeof dashboardSellerLayoutRoute
  dashboardSellerIndexRoute: typeof dashboardSellerIndexRoute
  dashboardSellerManageIndexRoute: typeof dashboardSellerManageIndexRoute
  dashboardSellerMypageIndexRoute: typeof dashboardSellerMypageIndexRoute
  dashboardSellerManageSettlementIdDetailRoute: typeof dashboardSellerManageSettlementIdDetailRoute
}

const dashboardSellerRouteChildren: dashboardSellerRouteChildren = {
  dashboardSellerLayoutRoute: dashboardSellerLayoutRoute,
  dashboardSellerIndexRoute: dashboardSellerIndexRoute,
  dashboardSellerManageIndexRoute: dashboardSellerManageIndexRoute,
  dashboardSellerMypageIndexRoute: dashboardSellerMypageIndexRoute,
  dashboardSellerManageSettlementIdDetailRoute:
    dashboardSellerManageSettlementIdDetailRoute,
}

const dashboardSellerRouteWithChildren = dashboardSellerRoute._addFileChildren(
  dashboardSellerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MakeProfileIndexRoute: MakeProfileIndexRoute,
  ManageAddressIndexRoute: ManageAddressIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  dashboardCustomerRoute: dashboardCustomerRouteWithChildren,
  dashboardRiderRoute: dashboardRiderRouteWithChildren,
  dashboardSellerRoute: dashboardSellerRouteWithChildren,
  MakeProfileCustomerIndexRoute: MakeProfileCustomerIndexRoute,
  MakeProfileRiderIndexRoute: MakeProfileRiderIndexRoute,
  MakeProfileSellerIndexRoute: MakeProfileSellerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
